# [ISS-428] Perfect Crypto does not compile on Ubuntu 14

[XML Source](../xml/ISS-428.xml)
<p></p>





Status|Resolution|Reporter|Assignee
------|----------|--------|--------
Closed|Duplicate|[Jerry Seeger](gseeger@apple.com)|[Rockford Wei]($rocky)





Created|Thu, 16 Mar 2017 16:29:54 -0400
-------|--------------
Updated|Mon, 24 Apr 2017 13:30:18 -0400
Resolved|Mon, 24 Apr 2017 11:25:16 -0400


## Comments




### Thu, 16 Mar 2017 16:31:12 -0400 / gseeger@apple.com 

<p><p>I don't have a lot of control over the environment I build into on Linux, and the latest version of Perfect Crypto (1.0.5) produces errors:</p>

<p>remote: /build/app/Packages/PerfectCrypto-1.0.5/Sources/OpenSSLInternal.swift:353:64: error: cannot convert value of type 'UnsafePointer&lt;UInt8&gt;?' to expected argument type 'UnsafeMutablePointer&lt;UInt8&gt;!'<br/>
remote:                 guard 1 == EVP_DigestVerifyFinal(ctx, signature.baseAddress?.assumingMemoryBound(to: UInt8.self), mdLen) else {<br/>
remote:                                                       ~~~~~~~~~~~~~~~~~~~~~~<sub>^</sub>~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~<br/>
remote: /usr/include/openssl/bn.h:187:19: error: integer literal is too large to be represented in any integer type<br/>
remote: #define BN_MASK         (0xffffffffffffffffffffffffffffffffLL)<br/>
remote:                          ^<br/>
remote: /build/app/Packages/PerfectCrypto-1.0.5/Sources/OpenSSLInternal.swift:381:31: error: use of unresolved identifier 'EVP_des_ede3_wrap'<br/>
remote:                 case .des_ede3_wrap:    return EVP_des_ede3_wrap()<br/>
remote:                                                ^~~~~~~~~~~~~~~~~<br/>
remote: /build/app/Packages/PerfectCrypto-1.0.5/Sources/OpenSSLInternal.swift:409:31: error: use of unresolved identifier 'EVP_aes_128_wrap'<br/>
remote:                 case .aes_128_wrap:             return EVP_aes_128_wrap()<br/>
remote:                                                        ^~~~~~~~~~~~~~~~<br/>
remote: /build/app/Packages/PerfectCrypto-1.0.5/Sources/OpenSSLInternal.swift:419:31: error: use of unresolved identifier 'EVP_aes_192_wrap'<br/>
remote:                 case .aes_192_wrap:             return EVP_aes_192_wrap()<br/>
remote:                                                        ^~~~~~~~~~~~~~~~<br/>
remote: /build/app/Packages/PerfectCrypto-1.0.5/Sources/OpenSSLInternal.swift:430:31: error: use of unresolved identifier 'EVP_aes_256_wrap'<br/>
remote:                 case .aes_256_wrap:             return EVP_aes_256_wrap()<br/>
remote:                                                        ^~~~~~~~~~~~~~~~<br/>
remote: /build/app/Packages/PerfectCrypto-1.0.5/Sources/OpenSSLInternal.swift:433:41: error: use of unresolved identifier 'EVP_aes_128_cbc_hmac_sha256'<br/>
remote:                 case .aes_128_cbc_hmac_sha256:  return EVP_aes_128_cbc_hmac_sha256()<br/>
remote:                                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~<br/>
remote: COpenSSL.EVP_aes_128_cbc_hmac_sha1:1:13: note: did you mean 'EVP_aes_128_cbc_hmac_sha1'?<br/>
remote: public func EVP_aes_128_cbc_hmac_sha1() -&gt; UnsafePointer&lt;EVP_CIPHER&gt;!<br/>
remote:             ^<br/>
remote: /build/app/Packages/PerfectCrypto-1.0.5/Sources/OpenSSLInternal.swift:434:41: error: use of unresolved identifier 'EVP_aes_256_cbc_hmac_sha256'<br/>
remote:                 case .aes_256_cbc_hmac_sha256:  return EVP_aes_256_cbc_hmac_sha256()<br/>
remote:                                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~<br/>
remote: COpenSSL.EVP_aes_256_cbc_hmac_sha1:1:13: note: did you mean 'EVP_aes_256_cbc_hmac_sha1'?<br/>
remote: public func EVP_aes_256_cbc_hmac_sha1() -&gt; UnsafePointer&lt;EVP_CIPHER&gt;!<br/>
remote:             ^<br/>
remote: /build/app/Packages/PerfectCrypto-1.0.5/Sources/ByteIO.swift:282:43: error: cannot convert value of type 'UnsafeRawPointer?' to expected argument type 'UnsafeMutableRawPointer!'<br/>
remote:                 super.init(bio: BIO_new_mem_buf(pointer.baseAddress, Int32(pointer.count)))<br/>
remote:                                                 ~~~~~~~<sub>^</sub>~~~~~~~~~<br/>
remote: /build/app/Packages/PerfectCrypto-1.0.5/Sources/ByteIO.swift:363:34: error: cannot convert value of type 'String' to expected argument type 'UnsafeMutablePointer&lt;Int8&gt;!'<br/>
remote:                 super.init(bio: BIO_new_accept(name))<br/>
remote:                                                ^~~~<br/>
remote: /build/app/Packages/PerfectCrypto-1.0.5/Sources/ByteIO.swift:394:35: error: cannot convert value of type 'String' to expected argument type 'UnsafeMutablePointer&lt;Int8&gt;!'<br/>
remote:                 super.init(bio: BIO_new_connect(name))<br/>
remote:                                                 ^~~~</p></p>


### Mon, 24 Apr 2017 11:25:16 -0400 / rocky 

<p><p>Hi, please check <a href="http://jira.perfect.org:8080/browse/ISS-448" title="PerfectCrypto" class="issue-link" data-issue-key="ISS-448"><del>ISS-448</del></a> for solution. Thanks.</p></p>


### Mon, 24 Apr 2017 13:24:40 -0400 / gseeger@apple.com 

<p><p>I do not have permission to view that request. As a result of being unable to compile and not getting a response from you guys for weeks, I was forced to switch to Kitara, which made me a little sad.</p></p>


### Mon, 24 Apr 2017 13:30:18 -0400 / rocky 

<p><p>Hi Jerry, here is a community solution:</p>

<p>PerfectCrypto relies on openssl 1.0.2. The official repository only has v1.0.1. I followed this instructions to install openssl v 1.0.2 <a href="https://gist.github.com/mbejda/a1dabc45b32aaf8b25ae5e8d05923518" class="external-link" rel="nofollow">https://gist.github.com/mbejda/a1dabc45b32aaf8b25ae5e8d05923518</a> and I was able to compile PerfectCrypto.</p>

<p> </p></p>


